#!/usr/bin/env python3

# Copyright (c) Arduino s.r.l. and/or its affiliated companies
# SPDX-License-Identifier: Apache-2.0

"""PySide6 viewer for <variant>.kconfig.json snapshots generated by cli.py.

Usage:
    gui.py [file_or_dir ...]

Loads snapshot files (or every *.kconfig.json in a directory) as columns in
a variant-vs-symbol matrix, with simple filters. Never touches CMake/
kconfiglib itself: it only reads files cli.py already generated.
"""

import argparse
import signal
import sys

from PySide6.QtCore import (
    QAbstractTableModel,
    QModelIndex,
    QSortFilterProxyModel,
    Qt,
)
from PySide6.QtGui import QColor, QFontDatabase
from PySide6.QtWidgets import (
    QAbstractItemView,
    QApplication,
    QCheckBox,
    QComboBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMainWindow,
    QSizePolicy,
    QTableView,
    QVBoxLayout,
    QWidget,
)

from kconfig_explorer import model as km

DIFF_COLOR = QColor(255, 235, 205)
MISSING_COLOR = QColor(190, 190, 190)
SCALE_LOW_COLOR = QColor(173, 216, 230)   # light blue: low / "n"
SCALE_MID_COLOR = QColor(152, 224, 152)   # light green: middle / all-equal
SCALE_HIGH_COLOR = QColor(255, 191, 128)  # light orange: high / "y"

BOOL_LEVELS = {"n": 0.0, "m": 0.5, "y": 1.0}
NUMERIC_TYPES = ("int", "hex")
BOOL_TYPES = ("bool", "tristate")

CONFIG_PREFIX = "CONFIG_"


def display_name(name):
    if name.startswith(CONFIG_PREFIX):
        return name[len(CONFIG_PREFIX):]
    return name


def _scale_color(t):
    t = max(0.0, min(1.0, t))
    if t <= 0.5:
        low, high, local_t = SCALE_LOW_COLOR, SCALE_MID_COLOR, t / 0.5
    else:
        low, high, local_t = SCALE_MID_COLOR, SCALE_HIGH_COLOR, (t - 0.5) / 0.5
    return QColor(
        round(low.red() + (high.red() - low.red()) * local_t),
        round(low.green() + (high.green() - low.green()) * local_t),
        round(low.blue() + (high.blue() - low.blue()) * local_t),
    )


def _numeric_value(value):
    try:
        return int(value, 0)
    except (TypeError, ValueError):
        return None


def _display_value(sym):
    """The value to show/color/compare in the matrix: an unset (kind ==
    "unset", value is None) bool/tristate symbol reads as "n" there, same
    as an explicit "n" would — Kconfig itself treats "not set" and "n" as
    the same thing for bools. The why-panel still shows the real kind
    ("unset") and (not set), this only affects the matrix cell."""

    if sym["value"] is None and sym["type"] in BOOL_TYPES:
        return "n"
    return sym["value"]


class KconfigTableModel(QAbstractTableModel):
    """Row per symbol name, one column per loaded variant. The Symbol/Type
    label lives in the vertical (row) header instead of being its own
    data column(s) — Qt's vertical header is already pinned to the left
    and never scrolls horizontally, so it does the "frozen column" job
    for free."""

    def __init__(self, snapshots):
        super().__init__()
        self.snapshots = {}
        self.variant_names = []
        self.symbol_names = []
        self.symbol_types = {}
        self.numeric_ranges = {}
        self.differing = set()
        self.current_row = -1
        self.collapsed_columns = set()
        self.set_snapshots(snapshots)

    def set_snapshots(self, snapshots):
        self.beginResetModel()
        self.snapshots = snapshots
        self.variant_names = list(snapshots.keys())
        self.symbol_names = km.union_symbol_names(snapshots)
        self.differing = self._compute_differing()
        self.symbol_types = {
            name: self._type_for(name) for name in self.symbol_names
        }
        self.numeric_ranges = {
            name: self._numeric_range_for(name)
            for name in self.symbol_names
            if self.symbol_types[name] in NUMERIC_TYPES
        }
        self.current_row = -1
        self.endResetModel()

    def set_current_row(self, row):
        """Bolds the given row's header label (Symbol/Type), used to
        highlight whichever row is currently selected in the table."""

        if row == self.current_row:
            return
        old_row = self.current_row
        self.current_row = row
        if 0 <= old_row < len(self.symbol_names):
            self.headerDataChanged.emit(Qt.Vertical, old_row, old_row)
        if 0 <= row < len(self.symbol_names):
            self.headerDataChanged.emit(Qt.Vertical, row, row)

    def set_collapsed_columns(self, cols):
        """Grays out the header label and cell contents of collapsed
        columns (see MainWindow._on_column_header_clicked)."""

        cols = set(cols)
        changed = self.collapsed_columns.symmetric_difference(cols)
        if not changed:
            return
        self.collapsed_columns = cols
        for col in changed:
            self.headerDataChanged.emit(Qt.Horizontal, col, col)
            if self.rowCount() > 0:
                self.dataChanged.emit(
                    self.index(0, col),
                    self.index(self.rowCount() - 1, col),
                    [Qt.ForegroundRole],
                )

    def _compute_differing(self):
        """Like model.differing_symbols(), but comparing displayed values
        (so an unset bool reads as "n", matching an explicit "n" instead
        of always counting as different from it)."""

        differing = set()
        for name in self.symbol_names:
            values = set()
            for snap in self.snapshots.values():
                sym = snap["symbols"].get(name)
                values.add(None if sym is None else _display_value(sym))
            if len(values) > 1:
                differing.add(name)
        return differing

    def _type_for(self, name):
        for snap in self.snapshots.values():
            sym = snap["symbols"].get(name)
            if sym is not None:
                return sym["type"]
        return ""

    def _numeric_range_for(self, name):
        values = [
            _numeric_value(sym["value"])
            for snap in self.snapshots.values()
            for sym in [snap["symbols"].get(name)]
            if sym is not None
        ]
        values = [v for v in values if v is not None]
        if not values:
            return None
        return min(values), max(values)

    def _color_level(self, name, sym):
        """Returns a 0..1 "how high on the low->high scale" fraction for a
        bool/tristate/int/hex cell, or None if not applicable (wrong type,
        unparsable value, or no numeric spread to compare against)."""

        sym_type = self.symbol_types[name]

        if sym_type in BOOL_TYPES:
            return BOOL_LEVELS.get(_display_value(sym))

        if sym_type in NUMERIC_TYPES:
            value = _numeric_value(sym["value"])
            value_range = self.numeric_ranges.get(name)
            if value is None or value_range is None:
                return None
            low, high = value_range
            if high == low:
                return 0.5
            return (value - low) / (high - low)

        return None

    def rowCount(self, parent=QModelIndex()):
        return 0 if parent.isValid() else len(self.symbol_names)

    def columnCount(self, parent=QModelIndex()):
        return 0 if parent.isValid() else len(self.variant_names)

    def headerData(self, section, orientation, role=Qt.DisplayRole):
        if orientation == Qt.Horizontal:
            if role == Qt.DisplayRole:
                return self.variant_names[section]
            if role == Qt.ForegroundRole and section in self.collapsed_columns:
                return QColor(Qt.gray)
            return None

        # Vertical (row) header: "SYMBOL (type)", bolded for the current row.
        name = self.symbol_names[section]
        if role == Qt.DisplayRole:
            return f"{display_name(name)}  ({self.symbol_types[name]})"
        if role == Qt.FontRole:
            font = QFontDatabase.systemFont(QFontDatabase.FixedFont)
            font.setBold(section == self.current_row)
            return font
        return None

    def _symbol_for(self, row, col):
        name = self.symbol_names[row]
        variant = self.variant_names[col]
        return name, variant, self.snapshots[variant]["symbols"].get(name)

    def data(self, index, role=Qt.DisplayRole):
        if not index.isValid():
            return None

        row, col = index.row(), index.column()
        name, variant, sym = self._symbol_for(row, col)

        if role == Qt.DisplayRole:
            if sym is None:
                return "—"
            value = _display_value(sym)
            if value is None:
                return ""
            if self.symbol_types[name] == "string":
                return f'"{value}"'
            if sym["value"] is None and self.symbol_types[name] in BOOL_TYPES:
                # Unset reads as "n" (see _display_value), but parenthesize
                # it so it's visually distinct from an explicit "n".
                return f"({value})"
            return value

        if role == Qt.ForegroundRole and col in self.collapsed_columns:
            return QColor(Qt.gray)

        if role == Qt.BackgroundRole:
            if sym is None:
                return MISSING_COLOR
            level = self._color_level(name, sym)
            if level is not None:
                return _scale_color(level)
            if self.symbol_types[name] == "string":
                return DIFF_COLOR if name in self.differing else SCALE_MID_COLOR
            if name in self.differing:
                return DIFF_COLOR

        if role == Qt.TextAlignmentRole:
            if sym is None:
                # Every "not present" cell looks the same, alignment
                # included, regardless of what type it would've been.
                return Qt.AlignCenter
            sym_type = self.symbol_types[name]
            if sym_type in BOOL_TYPES:
                return Qt.AlignCenter
            if sym_type in NUMERIC_TYPES:
                return Qt.AlignRight | Qt.AlignVCenter
            return Qt.AlignLeft | Qt.AlignVCenter

        if role == Qt.FontRole:
            if sym is None or self.symbol_types[name] != "string":
                # Always the same font for "not present" cells regardless
                # of type, and a fixed-width font for anything but string
                # values, so bool/int/hex line up.
                return QFontDatabase.systemFont(QFontDatabase.FixedFont)

        return None

    def symbol_entry(self, row, col):
        return self._symbol_for(row, col)


class FilterProxyModel(QSortFilterProxyModel):
    def __init__(self):
        super().__init__()
        self.name_filter = ""
        self.only_assigned = False
        self.hide_logs = False
        self.diff_filter = "any"
        self.type_filter = "any"
        self.kind_filter = "any"

    def set_filters(self, **kwargs):
        for key, value in kwargs.items():
            setattr(self, key, value)
        self.invalidateFilter()

    def filterAcceptsRow(self, source_row, source_parent):
        src = self.sourceModel()
        name = src.symbol_names[source_row]

        if self.name_filter and self.name_filter.lower() not in display_name(name).lower():
            return False

        if self.hide_logs and "_LOG_LEVEL" in name:
            return False

        if src.collapsed_columns and not self._present_in_expanded_column(src, name):
            return False

        if self.diff_filter == "differing" and name not in src.differing:
            return False
        if self.diff_filter == "same" and name in src.differing:
            return False

        needs_variant_check = (
            self.only_assigned
            or self.type_filter != "any"
            or self.kind_filter != "any"
        )
        if needs_variant_check and not self._any_variant_matches(src, name):
            return False

        return True

    def _any_variant_matches(self, src, name):
        for variant in src.variant_names:
            sym = src.snapshots[variant]["symbols"].get(name)
            if sym is None:
                continue
            if self.only_assigned and sym["kind"] != "assign":
                continue
            if self.type_filter != "any" and sym["type"] != self.type_filter:
                continue
            if self.kind_filter != "any" and sym["kind"] != self.kind_filter:
                continue
            return True
        return False

    def _present_in_expanded_column(self, src, name):
        """A row whose symbol only has a value in collapsed columns isn't
        useful to show — the user has minimized those columns precisely
        because they're not what they're looking at right now."""

        for col, variant in enumerate(src.variant_names):
            if col in src.collapsed_columns:
                continue
            if src.snapshots[variant]["symbols"].get(name) is not None:
                return True
        return False


class MainWindow(QMainWindow):
    def __init__(self, snapshots):
        super().__init__()
        self.setWindowTitle("Kconfig Explorer")

        self.table_model = KconfigTableModel(snapshots)
        self.proxy = FilterProxyModel()
        self.proxy.setSourceModel(self.table_model)

        self.table = QTableView()
        self.table.setModel(self.proxy)
        # No range selection: click/drag only ever moves the current cell,
        # one at a time, instead of selecting a rectangle of cells.
        self.table.setSelectionMode(QAbstractItemView.SingleSelection)
        # Tab/Shift+Tab switch focus between controls (filter bar, tab bar,
        # table) instead of moving the current cell — Qt's default here is
        # cell-to-cell, which breaks normal keyboard navigation between
        # widgets.
        self.table.setTabKeyNavigation(False)
        # The vertical header (Symbol/Type label) is Qt's own frozen-column
        # equivalent: always pinned to the left, never scrolls
        # horizontally. Its width is set explicitly in _autosize_row_header()
        # instead of QHeaderView.ResizeToContents: that mode resizes ROW
        # HEIGHT (sections, for a vertical header, are rows) by computing a
        # sizeHint from cell content across the whole row — with thousands
        # of rows that means thousands of round-trips into our Python
        # data(), which took 15+ seconds just to show the window.
        self.table.selectionModel().currentChanged.connect(self._on_current_changed)

        # Column collapse/expand-to-uniform-width state (see
        # _on_column_header_clicked/_on_column_resized).
        self.collapsed_columns = set()
        self._current_column_width = 0
        self._resizing_programmatically = False
        self.table.horizontalHeader().sectionClicked.connect(
            self._on_column_header_clicked
        )
        self.table.horizontalHeader().sectionResized.connect(
            self._on_column_resized
        )

        self._build_filter_bar()

        central = QWidget()
        layout = QVBoxLayout(central)
        layout.addWidget(self.filter_widget, 0)
        layout.addWidget(self.table, 1)
        self.setCentralWidget(central)

        self._autosize_columns()
        self._autosize_row_header()

    def _build_filter_bar(self):
        self.name_edit = QLineEdit()
        self.name_edit.setPlaceholderText("Filter by symbol name...")
        self.name_edit.textChanged.connect(self._on_filters_changed)

        self.only_assigned_check = QCheckBox("Only user-set")
        self.only_assigned_check.setToolTip(
            "Symbol was explicitly assigned in a .conf file (board "
            "defconfig, variant .conf, or prj.conf) — kind == assign."
        )
        self.only_assigned_check.stateChanged.connect(self._on_filters_changed)

        self.hide_logs_check = QCheckBox("Hide logs")
        self.hide_logs_check.setToolTip(
            'Hide symbols whose name contains "_LOG_LEVEL" '
            "(e.g. CONFIG_ADC_LOG_LEVEL_INF) — noisy, rarely of interest."
        )
        self.hide_logs_check.stateChanged.connect(self._on_filters_changed)

        self.diff_combo = QComboBox()
        self.diff_combo.addItems(["any", "same", "differing"])
        self.diff_combo.setToolTip(
            "any: no filter. same: value identical across all loaded "
            "variants. differing: value differs across loaded variants."
        )
        self.diff_combo.currentTextChanged.connect(self._on_filters_changed)

        self.type_combo = QComboBox()
        self.type_combo.addItems(["any", "bool", "tristate", "int", "hex", "string"])
        self.type_combo.currentTextChanged.connect(self._on_filters_changed)

        self.kind_combo = QComboBox()
        self.kind_combo.addItems(
            ["any", "unset", "default", "assign", "select", "imply"]
        )
        self.kind_combo.currentTextChanged.connect(self._on_filters_changed)

        bar = QHBoxLayout()
        bar.addWidget(self.name_edit)
        bar.addWidget(self.only_assigned_check)
        bar.addWidget(self.hide_logs_check)
        bar.addWidget(QLabel("Diff:"))
        bar.addWidget(self.diff_combo)
        bar.addWidget(QLabel("Type:"))
        bar.addWidget(self.type_combo)
        bar.addWidget(QLabel("Kind:"))
        bar.addWidget(self.kind_combo)

        self.filter_widget = QWidget()
        self.filter_widget.setLayout(bar)
        self.filter_widget.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)

        # Default view: only symbols the user actually assigned somewhere,
        # not every symbol that merely got a default/select/imply value,
        # and hide log-level noise. Set last, once every filter widget
        # _on_filters_changed() reads actually exists.
        self.only_assigned_check.setChecked(True)
        self.hide_logs_check.setChecked(True)

    def _on_filters_changed(self, *_args):
        self.proxy.set_filters(
            name_filter=self.name_edit.text(),
            only_assigned=self.only_assigned_check.isChecked(),
            hide_logs=self.hide_logs_check.isChecked(),
            diff_filter=self.diff_combo.currentText(),
            type_filter=self.type_combo.currentText(),
            kind_filter=self.kind_combo.currentText(),
        )

    def _on_current_changed(self, current, _previous):
        if not current.isValid():
            return
        source_index = self.proxy.mapToSource(current)
        self.table_model.set_current_row(source_index.row())

    def _autosize_columns(self):
        """Every non-collapsed variant column gets one uniform width: just
        wide enough for the widest variant name, cell contents ignored, so
        a long value never stretches a column. Collapsed columns (see
        _on_column_header_clicked) are left alone."""

        count = self.table_model.columnCount()
        if count == 0:
            return

        metrics = self.table.horizontalHeader().fontMetrics()
        padding = 24
        widest = max(
            metrics.horizontalAdvance(str(self.table_model.headerData(c, Qt.Horizontal) or ""))
            for c in range(count)
        )
        width = widest + padding
        self._current_column_width = width
        self._set_columns_width(
            (c for c in range(count) if c not in self.collapsed_columns), width
        )

    def _set_columns_width(self, cols, width):
        """Sets width on the given columns without triggering
        _on_column_resized's "propagate to every other column" behavior —
        used for autosizing and for collapse/expand, which shouldn't
        cascade into resizing unrelated columns."""

        self._resizing_programmatically = True
        try:
            for col in cols:
                self.table.setColumnWidth(col, width)
        finally:
            self._resizing_programmatically = False

    def _on_column_header_clicked(self, logical_index):
        """Click a column header to collapse it to a small square (just
        the header height wide) or restore it to the shared column
        width."""

        if logical_index in self.collapsed_columns:
            self.collapsed_columns.discard(logical_index)
            self._set_columns_width([logical_index], self._current_column_width)
        else:
            self.collapsed_columns.add(logical_index)
            square = self.table.horizontalHeader().height()
            self._set_columns_width([logical_index], square)
        self.table_model.set_collapsed_columns(self.collapsed_columns)
        self.proxy.invalidateFilter()

    def _on_column_resized(self, logical_index, _old_size, new_size):
        """Dragging one column resizes every other non-collapsed column to
        match, keeping them uniform (collapsed columns are left alone)."""

        if self._resizing_programmatically or logical_index in self.collapsed_columns:
            return

        self._current_column_width = new_size
        others = (
            c for c in range(self.table_model.columnCount())
            if c != logical_index and c not in self.collapsed_columns
        )
        self._set_columns_width(others, new_size)

    def _autosize_row_header(self):
        """Sizes the vertical header (Symbol/Type label) to the widest
        label via plain text metrics — not QHeaderView.ResizeToContents,
        which computes a sizeHint per row from cell content across the
        whole row and is catastrophically slow with thousands of rows.
        Uses resize() rather than setFixedWidth() so the user can still
        drag it wider/narrower afterward (resize mode stays Interactive)."""

        row_count = self.table_model.rowCount()
        if row_count == 0:
            return

        header = self.table.verticalHeader()
        metrics = header.fontMetrics()
        padding = 24
        widest = max(
            metrics.horizontalAdvance(str(self.table_model.headerData(r, Qt.Vertical) or ""))
            for r in range(row_count)
        )
        header.resize(widest + padding, header.height())



def parse_args(argv):
    parser = argparse.ArgumentParser(
        prog="gui.py",
        description="PySide6 viewer for <variant>.kconfig.json snapshots.",
    )
    parser.add_argument(
        "paths",
        nargs="*",
        metavar="FILE_OR_DIR",
        help="snapshot file(s), or folder(s) containing *.kconfig.json files",
    )
    return parser.parse_args(argv)


def main():
    args = parse_args(sys.argv[1:])

    # Parse our own args first so --help/-h works without Qt swallowing it or
    # complaining about an unrecognized option; only pass argv[0] to Qt.
    app = QApplication(sys.argv[:1])

    # Qt's C++ event loop never yields back to the Python interpreter, so
    # Python's own SIGINT handler (which needs interpreter reentry to raise
    # KeyboardInterrupt) never gets a chance to run: Ctrl-C in the terminal
    # is otherwise silently ignored. Restoring the OS default handler makes
    # the process terminate immediately on SIGINT, like any other CLI tool.
    signal.signal(signal.SIGINT, signal.SIG_DFL)

    snapshots = {}
    for path in args.paths:
        snapshots.update(km.load_snapshots(path))

    window = MainWindow(snapshots)
    window.resize(1200, 700)
    window.show()
    window.table.setFocus()

    sys.exit(app.exec())


if __name__ == "__main__":
    main()
