#!/usr/bin/env python3

# Copyright (c) Arduino s.r.l. and/or its affiliated companies
# SPDX-License-Identifier: Apache-2.0

"""PySide6 viewer for <variant>.kconfig.json snapshots generated by cli.py.

Usage:
    gui.py [file_or_dir ...]
    gui.py --diff <dir> <dir> [<dir> ...]

Loads snapshot files (or every *.kconfig.json in a directory) as columns in
a variant-vs-symbol matrix, with simple filters and a "why" panel showing
the kind/location for the selected cell. Never touches CMake/kconfiglib
itself: it only reads files cli.py already generated.

--diff instead expects several directories with matching *.kconfig.json
filenames (e.g. two 'cli.py generate --out' runs to compare), and opens
one tab per unique filename, one column per directory.
"""

import argparse
import html
import math
import os
import re
import signal
import sys
from pathlib import Path

from PySide6.QtCore import (
    QAbstractTableModel,
    QModelIndex,
    QPoint,
    QRect,
    QSortFilterProxyModel,
    Qt,
)
from PySide6.QtGui import QColor, QFontDatabase, QTextDocument
from PySide6.QtWidgets import (
    QAbstractItemView,
    QApplication,
    QCheckBox,
    QComboBox,
    QFrame,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMainWindow,
    QSizePolicy,
    QTabBar,
    QTableView,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from kconfig_explorer import model as km

DIFF_COLOR = QColor(255, 235, 205)
MISSING_COLOR = QColor(190, 190, 190)
SCALE_LOW_COLOR = QColor(173, 216, 230)   # light blue: low / "n"
SCALE_MID_COLOR = QColor(152, 224, 152)   # light green: middle / all-equal
SCALE_HIGH_COLOR = QColor(255, 191, 128)  # light orange: high / "y"

BOOL_LEVELS = {"n": 0.0, "m": 0.5, "y": 1.0}
NUMERIC_TYPES = ("int", "hex")
BOOL_TYPES = ("bool", "tristate")

CONFIG_PREFIX = "CONFIG_"


def _find_workspace_root():
    """Parent directory of the ArduinoCore-zephyr checkout containing this
    script — e.g. /home/x/Work/zephyr, which also holds the zephyr and
    modules checkouts as siblings. This script's own path relative to
    that checkout is fixed
    (<workspace>/ArduinoCore-zephyr/extra/kconfig-explorer/gui.py), so
    just count parents rather than searching the path for a name."""

    return str(Path(__file__).resolve().parents[3])


WORKSPACE_ROOT = _find_workspace_root()


def strip_workspace_root(file_path):
    """Locations inside WORKSPACE_ROOT (ArduinoCore-zephyr, zephyr,
    modules, ...) get shown relative to it; anything else (the toolchain,
    a temp build dir, ...) stays a full path starting with "/". Also
    collapses "foo/../bar" segments (e.g. loader/Kconfig sourcing things
    as "../variants/...") since those are just noise for a human reader."""

    file_path = os.path.normpath(file_path)
    if WORKSPACE_ROOT and (
        file_path == WORKSPACE_ROOT or file_path.startswith(WORKSPACE_ROOT + os.sep)
    ):
        return file_path[len(WORKSPACE_ROOT):].lstrip(os.sep)
    return file_path


_VARIANT_CONF_RE = re.compile(r"(?:^|/)variants/([^/]+)/\1\.conf$")
_PRJ_CONF_RE = re.compile(r"(?:^|/)loader/prj\.conf$")


def simplify_known_path(path):
    """A board's own variants/<X>/<X>.conf and the loader's prj.conf are single
    well-known files - the variant/board name (for the conf) or "prj.conf"
    itself already identifies them, so the long enclosing path is just noise."""

    match = _VARIANT_CONF_RE.search(path)
    if match:
        return f"{match.group(1)}.conf"
    if _PRJ_CONF_RE.search(path):
        return "prj.conf"
    return path


def display_name(name):
    if name.startswith(CONFIG_PREFIX):
        return name[len(CONFIG_PREFIX):]
    return name


def _scale_color(t):
    t = max(0.0, min(1.0, t))
    if t <= 0.5:
        low, high, local_t = SCALE_LOW_COLOR, SCALE_MID_COLOR, t / 0.5
    else:
        low, high, local_t = SCALE_MID_COLOR, SCALE_HIGH_COLOR, (t - 0.5) / 0.5
    return QColor(
        round(low.red() + (high.red() - low.red()) * local_t),
        round(low.green() + (high.green() - low.green()) * local_t),
        round(low.blue() + (high.blue() - low.blue()) * local_t),
    )


def _numeric_value(value):
    try:
        return int(value, 0)
    except (TypeError, ValueError):
        return None


def _display_value(sym):
    """The value to show/color/compare in the matrix: an unset (kind ==
    "unset", value is None) bool/tristate symbol reads as "n" there, same
    as an explicit "n" would — Kconfig itself treats "not set" and "n" as
    the same thing for bools. The why-panel still shows the real kind
    ("unset") and (not set), this only affects the matrix cell."""

    if sym["value"] is None and sym["type"] in BOOL_TYPES:
        return "n"
    return sym["value"]


class KconfigTableModel(QAbstractTableModel):
    """Row per symbol name, one column per loaded variant. The Symbol/Type
    label lives in the vertical (row) header instead of being its own
    data column(s) — Qt's vertical header is already pinned to the left
    and never scrolls horizontally, so it does the "frozen column" job
    for free."""

    def __init__(self, snapshots):
        super().__init__()
        self.snapshots = {}
        self.variant_names = []
        self.symbol_names = []
        self.symbol_types = {}
        self.numeric_ranges = {}
        self.differing = set()
        self.current_row = -1
        self.collapsed_columns = set()
        self.set_snapshots(snapshots)

    def set_snapshots(self, snapshots):
        self.beginResetModel()
        self.snapshots = snapshots
        self.variant_names = list(snapshots.keys())
        self.symbol_names = km.union_symbol_names(snapshots)
        self.differing = self._compute_differing()
        self.symbol_types = {
            name: self._type_for(name) for name in self.symbol_names
        }
        self.numeric_ranges = {
            name: self._numeric_range_for(name)
            for name in self.symbol_names
            if self.symbol_types[name] in NUMERIC_TYPES
        }
        self.current_row = -1
        self.endResetModel()

    def set_current_row(self, row):
        """Bolds the given row's header label (Symbol/Type), used to
        highlight whichever row is currently selected in the table."""

        if row == self.current_row:
            return
        old_row = self.current_row
        self.current_row = row
        if 0 <= old_row < len(self.symbol_names):
            self.headerDataChanged.emit(Qt.Vertical, old_row, old_row)
        if 0 <= row < len(self.symbol_names):
            self.headerDataChanged.emit(Qt.Vertical, row, row)

    def set_collapsed_columns(self, cols):
        """Grays out the header label and cell contents of collapsed
        columns (see MainWindow._on_column_header_clicked)."""

        cols = set(cols)
        changed = self.collapsed_columns.symmetric_difference(cols)
        if not changed:
            return
        self.collapsed_columns = cols
        for col in changed:
            self.headerDataChanged.emit(Qt.Horizontal, col, col)
            if self.rowCount() > 0:
                self.dataChanged.emit(
                    self.index(0, col),
                    self.index(self.rowCount() - 1, col),
                    [Qt.ForegroundRole],
                )

    def _compute_differing(self):
        """Like model.differing_symbols(), but comparing displayed values
        (so an unset bool reads as "n", matching an explicit "n" instead
        of always counting as different from it)."""

        differing = set()
        for name in self.symbol_names:
            values = set()
            for snap in self.snapshots.values():
                sym = snap["symbols"].get(name)
                values.add(None if sym is None else _display_value(sym))
            if len(values) > 1:
                differing.add(name)
        return differing

    def _type_for(self, name):
        for snap in self.snapshots.values():
            sym = snap["symbols"].get(name)
            if sym is not None:
                return sym["type"]
        return ""

    def _numeric_range_for(self, name):
        values = [
            _numeric_value(sym["value"])
            for snap in self.snapshots.values()
            for sym in [snap["symbols"].get(name)]
            if sym is not None
        ]
        values = [v for v in values if v is not None]
        if not values:
            return None
        return min(values), max(values)

    def _color_level(self, name, sym):
        """Returns a 0..1 "how high on the low->high scale" fraction for a
        bool/tristate/int/hex cell, or None if not applicable (wrong type,
        unparsable value, or no numeric spread to compare against)."""

        sym_type = self.symbol_types[name]

        if sym_type in BOOL_TYPES:
            return BOOL_LEVELS.get(_display_value(sym))

        if sym_type in NUMERIC_TYPES:
            value = _numeric_value(sym["value"])
            value_range = self.numeric_ranges.get(name)
            if value is None or value_range is None:
                return None
            low, high = value_range
            if high == low:
                return 0.5
            return (value - low) / (high - low)

        return None

    def rowCount(self, parent=QModelIndex()):
        return 0 if parent.isValid() else len(self.symbol_names)

    def columnCount(self, parent=QModelIndex()):
        return 0 if parent.isValid() else len(self.variant_names)

    def headerData(self, section, orientation, role=Qt.DisplayRole):
        if orientation == Qt.Horizontal:
            if role == Qt.DisplayRole:
                return self.variant_names[section]
            if role == Qt.ForegroundRole and section in self.collapsed_columns:
                return QColor(Qt.gray)
            return None

        # Vertical (row) header: "SYMBOL (type)", bolded for the current row.
        name = self.symbol_names[section]
        if role == Qt.DisplayRole:
            return f"{display_name(name)}  ({self.symbol_types[name]})"
        if role == Qt.FontRole:
            font = QFontDatabase.systemFont(QFontDatabase.FixedFont)
            font.setBold(section == self.current_row)
            return font
        return None

    def _symbol_for(self, row, col):
        name = self.symbol_names[row]
        variant = self.variant_names[col]
        return name, variant, self.snapshots[variant]["symbols"].get(name)

    def data(self, index, role=Qt.DisplayRole):
        if not index.isValid():
            return None

        row, col = index.row(), index.column()
        name, variant, sym = self._symbol_for(row, col)

        if role == Qt.DisplayRole:
            if sym is None:
                return "—"
            value = _display_value(sym)
            if value is None:
                return ""
            if self.symbol_types[name] == "string":
                return f'"{value}"'
            if sym["value"] is None and self.symbol_types[name] in BOOL_TYPES:
                # Unset reads as "n" (see _display_value), but parenthesize
                # it so it's visually distinct from an explicit "n".
                return f"({value})"
            return value

        if role == Qt.ForegroundRole and col in self.collapsed_columns:
            return QColor(Qt.gray)

        if role == Qt.BackgroundRole:
            if sym is None:
                return MISSING_COLOR
            level = self._color_level(name, sym)
            if level is not None:
                return _scale_color(level)
            if self.symbol_types[name] == "string":
                return DIFF_COLOR if name in self.differing else SCALE_MID_COLOR
            if name in self.differing:
                return DIFF_COLOR

        if role == Qt.TextAlignmentRole:
            if sym is None:
                # Every "not present" cell looks the same, alignment
                # included, regardless of what type it would've been.
                return Qt.AlignCenter
            sym_type = self.symbol_types[name]
            if sym_type in BOOL_TYPES:
                return Qt.AlignCenter
            if sym_type in NUMERIC_TYPES:
                return Qt.AlignRight | Qt.AlignVCenter
            return Qt.AlignLeft | Qt.AlignVCenter

        if role == Qt.FontRole:
            if sym is None or self.symbol_types[name] != "string":
                # Always the same font for "not present" cells regardless
                # of type, and a fixed-width font for anything but string
                # values, so bool/int/hex line up.
                return QFontDatabase.systemFont(QFontDatabase.FixedFont)

        return None

    def symbol_entry(self, row, col):
        return self._symbol_for(row, col)


class FilterProxyModel(QSortFilterProxyModel):
    def __init__(self):
        super().__init__()
        self.name_filter = ""
        self.only_assigned = False
        self.hide_logs = False
        self.diff_filter = "any"
        self.type_filter = "any"
        self.kind_filter = "any"

    def set_filters(self, **kwargs):
        for key, value in kwargs.items():
            setattr(self, key, value)
        self.invalidateFilter()

    def filterAcceptsRow(self, source_row, source_parent):
        src = self.sourceModel()
        name = src.symbol_names[source_row]

        if self.name_filter and self.name_filter.lower() not in display_name(name).lower():
            return False

        if self.hide_logs and "_LOG_LEVEL" in name:
            return False

        if src.collapsed_columns and not self._present_in_expanded_column(src, name):
            return False

        if self.diff_filter == "differing" and name not in src.differing:
            return False
        if self.diff_filter == "same" and name in src.differing:
            return False

        needs_variant_check = (
            self.only_assigned
            or self.type_filter != "any"
            or self.kind_filter != "any"
        )
        if needs_variant_check and not self._any_variant_matches(src, name):
            return False

        return True

    def _any_variant_matches(self, src, name):
        for variant in src.variant_names:
            sym = src.snapshots[variant]["symbols"].get(name)
            if sym is None:
                continue
            if self.only_assigned and sym["kind"] != "assign":
                continue
            if self.type_filter != "any" and sym["type"] != self.type_filter:
                continue
            if self.kind_filter != "any" and sym["kind"] != self.kind_filter:
                continue
            return True
        return False

    def _present_in_expanded_column(self, src, name):
        """A row whose symbol only has a value in collapsed columns isn't
        useful to show — the user has minimized those columns precisely
        because they're not what they're looking at right now."""

        for col, variant in enumerate(src.variant_names):
            if col in src.collapsed_columns:
                continue
            if src.snapshots[variant]["symbols"].get(name) is not None:
                return True
        return False


def format_why(name, variant, sym):
    """Returns HTML for the details panel: bold name (and bold variant,
    but not the " @ " between them), then the fields as a two-column
    table (label column shrinks to content, value column stretches)."""

    shown_name = f"<tt>{html.escape(display_name(name))}</tt>"

    if variant is None:
        return f"<b>{shown_name}</b><br><br>(select a variant column to see details)"

    header = f"<b>{shown_name}</b> @ <b>{html.escape(variant)}</b>"
    if sym and sym["visibility"] != "y":
        header += " (hidden)"

    if sym is None:
        return f"{header}"

    if sym["value"] is None:
        shown_value = "(not set)" 
    else:
        shown_value = sym["value"]
        if sym["type"] == "string":
            # Show string values in quotes
            shown_value = f'"{shown_value}"'

    value_html = html.escape(str(shown_value))
    if sym["type"] != "string" and sym["value"] is not None:
        # Use fixed-width font for anything but a string value.
        value_html = f"<tt>{value_html}</tt>"

    fields = [
        ("Type", html.escape(str(sym["type"]))),
        ("Value", value_html),
        ("Kind", html.escape(str(sym["kind"]))),
    ]

    loc = sym.get("location")
    if loc is None:
        fields.append(("Location", "(none)"))
    elif loc["kind"] == "fileline":
        shown_file = simplify_known_path(strip_workspace_root(loc["file"]))
        fields.append(("Location", html.escape(f"{shown_file}:{loc['line']}")))
    elif loc["kind"] == "exprs":
        fields.append((
            "Active expressions",
            "<br>".join(html.escape(expr) for expr in loc["value"]),
        ))

    rows = "".join(
        '<tr><td style="white-space:nowrap; vertical-align:top; '
        f'padding-right:8px;">{html.escape(label)}:</td>'
        f'<td style="width:100%; vertical-align:top;">{value}</td></tr>'
        for label, value in fields
    )
    table = f'<table style="width:100%; border-collapse:collapse;">{rows}</table>'

    return f"{header}<br>{table}"


class FloatingDetailsPanel(QTextEdit):
    """A "stable tooltip" for symbol details: unlike a real QToolTip, it
    stays open and its text can be selected/copied. Sized to fit its own
    content and repositioned next to whatever cell is currently selected,
    instead of living in a fixed docked pane.

    Implemented as a plain CHILD widget of the main window (raised above
    its siblings), not a separate top-level window: a real top-level
    window's move() is silently ignored under Wayland (clients can't
    position top-level surfaces there — only the compositor decides,
    which is why it kept appearing centered on the parent regardless of
    where the selection was), and showing/hiding one repeatedly stole
    keyboard focus from the table even with Qt.WA_ShowWithoutActivating.
    A child widget has none of that: it's positioned within its parent's
    own coordinate space like any other widget, and setFocusPolicy(NoFocus)
    guarantees it can never take keyboard focus away from the table."""

    MIN_WIDTH = 220
    MIN_HEIGHT = 36
    GAP = 4

    def __init__(self, parent):
        super().__init__(parent)
        self.setReadOnly(True)
        self.setFocusPolicy(Qt.NoFocus)
        self.setTextInteractionFlags(Qt.TextSelectableByMouse | Qt.TextSelectableByKeyboard)
        self.setFrameShape(QFrame.Box)
        self.setLineWrapMode(QTextEdit.WidgetWidth)
        self.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        # Never let a scrollbar appear at all: if it did, it would eat into
        # the viewport width, wrapping text more than _fit_to_content()
        # accounted for — self-sizing is supposed to make scrolling
        # unnecessary in the first place.
        self.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.setStyleSheet("QTextEdit { background-color: lightyellow; }")
        self.hide()

    def show_near(self, avoid_rect, html_text):
        """avoid_rect: the selected cell's rect, in this widget's parent's
        coordinate space — the panel is placed clear of it, not on top.
        html_text: format_why()'s HTML output, used directly (it already
        has its own bold/table formatting)."""

        self.setHtml(html_text)
        self._fit_to_content(html_text)
        self.move(self._placement(avoid_rect))
        self.show()
        self.raise_()

    def _placement(self, avoid_rect):
        bounds = self.parentWidget().rect()

        x = min(avoid_rect.left(), bounds.right() - self.width())
        x = max(bounds.left(), x)

        y = avoid_rect.bottom() + self.GAP
        if y + self.height() > bounds.bottom():
            above = avoid_rect.top() - self.GAP - self.height()
            y = above if above >= bounds.top() else max(bounds.top(), bounds.bottom() - self.height())

        return QPoint(x, y)

    def _fit_to_content(self, html_text):
        # Measured on a throwaway QTextDocument, not self.document(): this
        # widget's own document is kept in sync with the *live* viewport
        # width (setLineWrapMode(WidgetWidth)), so measuring against it
        # mixes in whatever size the widget happened to have from the
        # previous selection — the same text could come out narrower or
        # wider (and wrap differently) depending on history. A standalone
        # document has no ties to this widget's current/previous size.
        margins = self.contentsMargins()
        measure_doc = QTextDocument()
        measure_doc.setDefaultFont(self.font())
        measure_doc.setHtml(html_text)

        # NOTE: idealWidth()/size() already bake in the document's own
        # documentMargin() (verified: idealWidth() of a plain single line
        # equals its font-metrics text width + 2*documentMargin()) — adding
        # it again here double-counts it. That inflated both the padding
        # subtracted back out of the chosen width (so long paths wrapped
        # more than needed, despite the box having room) and the padding
        # added to the height (extra blank space at the bottom).
        pad_x = 2 * self.frameWidth() + margins.left() + margins.right() + 2
        pad_y = 2 * self.frameWidth() + margins.top() + margins.bottom() + 2

        # Unconstrained (-1 = no wrap at all) so idealWidth() reflects the
        # text's true natural width. Constraining it to a fixed max first
        # (as this used to) means that if the content is wider than that,
        # the document is already wrapped by the time idealWidth() is
        # read, so it no longer reflects the actual longest line — the
        # computed width came out far too small, and long paths kept
        # wrapping even though the box had plenty of room left to grow.
        # No fixed cap here: only bounded by the parent window's own
        # width, so wrapping only ever happens if the line genuinely
        # can't fit in the window at all.
        max_width = max(self.MIN_WIDTH, self.parentWidget().width() - 2 * self.GAP)

        # ceil(), not int(): idealWidth() is fractional (e.g. 266.62), and
        # truncating it below its true value (266) then handing the text
        # back exactly that width forces the last word to wrap after all
        # — same line count, but now taller, purely from rounding down a
        # fraction of a pixel. Two texts with identical structure could
        # end up different heights just because one's ideal width happened
        # to truncate closer to the edge than the other's.
        measure_doc.setTextWidth(-1)
        width = min(max_width, max(self.MIN_WIDTH, math.ceil(measure_doc.idealWidth()) + pad_x))

        # Same reasoning as width: bounded by the parent window's own
        # height, not a fixed constant.
        max_height = max(self.MIN_HEIGHT, self.parentWidget().height() - 2 * self.GAP)

        measure_doc.setTextWidth(width - pad_x)
        height = min(
            max_height, max(self.MIN_HEIGHT, math.ceil(measure_doc.size().height()) + pad_y)
        )

        self.resize(width, height)


class MainWindow(QMainWindow):
    def __init__(self, tabs):
        super().__init__()
        self.setWindowTitle("Kconfig Explorer")

        self.tabs = tabs
        self.table_model = KconfigTableModel(tabs[0][1])
        self.proxy = FilterProxyModel()
        self.proxy.setSourceModel(self.table_model)

        self.table = QTableView()
        self.table.setModel(self.proxy)
        # No range selection: click/drag only ever moves the current cell,
        # one at a time, instead of selecting a rectangle of cells.
        self.table.setSelectionMode(QAbstractItemView.SingleSelection)
        # Tab/Shift+Tab switch focus between controls (filter bar, tab bar,
        # table) instead of moving the current cell — Qt's default here is
        # cell-to-cell, which breaks normal keyboard navigation between
        # widgets.
        self.table.setTabKeyNavigation(False)
        # The vertical header (Symbol/Type label) is Qt's own frozen-column
        # equivalent: always pinned to the left, never scrolls
        # horizontally. Its width is set explicitly in _autosize_row_header()
        # instead of QHeaderView.ResizeToContents: that mode resizes ROW
        # HEIGHT (sections, for a vertical header, are rows) by computing a
        # sizeHint from cell content across the whole row — with thousands
        # of rows that means thousands of round-trips into our Python
        # data(), which took 15+ seconds just to show the window.
        self.table.selectionModel().currentChanged.connect(self._on_current_changed)

        # Column collapse/expand-to-uniform-width state (see
        # _on_column_header_clicked/_on_column_resized).
        self.collapsed_columns = set()
        self._current_column_width = 0
        self._resizing_programmatically = False
        self.table.horizontalHeader().sectionClicked.connect(
            self._on_column_header_clicked
        )
        self.table.horizontalHeader().sectionResized.connect(
            self._on_column_resized
        )

        # Floating "stable tooltip" instead of a docked pane: follows the
        # current selection and auto-sizes to its content, but (unlike a
        # real QToolTip) stays open and its text can be selected/copied.
        self.why_panel = FloatingDetailsPanel(self)

        self._build_filter_bar()

        self.tab_bar = QTabBar()
        # Left-aligned, minimal size instead of the default of stretching
        # tabs to fill the whole window width.
        self.tab_bar.setExpanding(False)
        for title, _snapshots in tabs:
            self.tab_bar.addTab(title)

        central = QWidget()
        layout = QVBoxLayout(central)
        layout.addWidget(self.filter_widget, 0)
        layout.addWidget(self.tab_bar, 0, Qt.AlignLeft)
        layout.addWidget(self.table, 1)
        self.setCentralWidget(central)

        self.tab_bar.currentChanged.connect(self._on_tab_changed)

        self._autosize_columns()
        self._autosize_row_header()

    def _build_filter_bar(self):
        self.name_edit = QLineEdit()
        self.name_edit.setPlaceholderText("Filter by symbol name...")
        self.name_edit.textChanged.connect(self._on_filters_changed)

        self.only_assigned_check = QCheckBox("Only user-set")
        self.only_assigned_check.setToolTip(
            "Symbol was explicitly assigned in a .conf file (board "
            "defconfig, variant .conf, or prj.conf) — kind == assign."
        )
        self.only_assigned_check.stateChanged.connect(self._on_filters_changed)

        self.hide_logs_check = QCheckBox("Hide logs")
        self.hide_logs_check.setToolTip(
            'Hide symbols whose name contains "_LOG_LEVEL" '
            "(e.g. CONFIG_ADC_LOG_LEVEL_INF) — noisy, rarely of interest."
        )
        self.hide_logs_check.stateChanged.connect(self._on_filters_changed)

        self.diff_combo = QComboBox()
        self.diff_combo.addItems(["any", "same", "differing"])
        self.diff_combo.setToolTip(
            "any: no filter. same: value identical across all loaded "
            "variants. differing: value differs across loaded variants."
        )
        self.diff_combo.currentTextChanged.connect(self._on_filters_changed)

        self.type_combo = QComboBox()
        self.type_combo.addItems(["any", "bool", "tristate", "int", "hex", "string"])
        self.type_combo.currentTextChanged.connect(self._on_filters_changed)

        self.kind_combo = QComboBox()
        self.kind_combo.addItems(
            ["any", "unset", "default", "assign", "select", "imply"]
        )
        self.kind_combo.currentTextChanged.connect(self._on_filters_changed)

        bar = QHBoxLayout()
        bar.addWidget(self.name_edit)
        bar.addWidget(self.only_assigned_check)
        bar.addWidget(self.hide_logs_check)
        bar.addWidget(QLabel("Diff:"))
        bar.addWidget(self.diff_combo)
        bar.addWidget(QLabel("Type:"))
        bar.addWidget(self.type_combo)
        bar.addWidget(QLabel("Kind:"))
        bar.addWidget(self.kind_combo)

        self.filter_widget = QWidget()
        self.filter_widget.setLayout(bar)
        self.filter_widget.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)

        # Default view: only symbols the user actually assigned somewhere,
        # not every symbol that merely got a default/select/imply value,
        # and hide log-level noise. Set last, once every filter widget
        # _on_filters_changed() reads actually exists.
        self.only_assigned_check.setChecked(True)
        self.hide_logs_check.setChecked(True)

    def _on_filters_changed(self, *_args):
        self.proxy.set_filters(
            name_filter=self.name_edit.text(),
            only_assigned=self.only_assigned_check.isChecked(),
            hide_logs=self.hide_logs_check.isChecked(),
            diff_filter=self.diff_combo.currentText(),
            type_filter=self.type_combo.currentText(),
            kind_filter=self.kind_combo.currentText(),
        )

    def _on_current_changed(self, current, _previous):
        if not current.isValid():
            self.why_panel.hide()
            return
        source_index = self.proxy.mapToSource(current)
        self.table_model.set_current_row(source_index.row())
        name, variant, sym = self.table_model.symbol_entry(
            source_index.row(), source_index.column()
        )

        cell_rect = self.table.visualRect(current)
        cell_rect_in_window = QRect(
            self.table.viewport().mapTo(self, cell_rect.topLeft()), cell_rect.size()
        )
        self.why_panel.show_near(cell_rect_in_window, format_why(name, variant, sym))

    def _on_tab_changed(self, index):
        _title, snapshots = self.tabs[index]
        self.table_model.set_snapshots(snapshots)
        self.collapsed_columns = set()
        self.table_model.set_collapsed_columns(self.collapsed_columns)
        self.why_panel.hide()
        self._autosize_columns()
        self._autosize_row_header()

    def keyPressEvent(self, event):
        # why_panel can never have keyboard focus itself (NoFocus), so
        # Escape is handled here: unhandled key events bubble up from the
        # focused child (the table) to the top-level window in Qt.
        if event.key() == Qt.Key_Escape and self.why_panel.isVisible():
            self.why_panel.hide()
            event.accept()
            return
        super().keyPressEvent(event)

    def _autosize_columns(self):
        """Every non-collapsed variant column gets one uniform width: just
        wide enough for the widest variant name, cell contents ignored, so
        a long value never stretches a column. Collapsed columns (see
        _on_column_header_clicked) are left alone."""

        count = self.table_model.columnCount()
        if count == 0:
            return

        metrics = self.table.horizontalHeader().fontMetrics()
        padding = 24
        widest = max(
            metrics.horizontalAdvance(str(self.table_model.headerData(c, Qt.Horizontal) or ""))
            for c in range(count)
        )
        width = widest + padding
        self._current_column_width = width
        self._set_columns_width(
            (c for c in range(count) if c not in self.collapsed_columns), width
        )

    def _set_columns_width(self, cols, width):
        """Sets width on the given columns without triggering
        _on_column_resized's "propagate to every other column" behavior —
        used for autosizing and for collapse/expand, which shouldn't
        cascade into resizing unrelated columns."""

        self._resizing_programmatically = True
        try:
            for col in cols:
                self.table.setColumnWidth(col, width)
        finally:
            self._resizing_programmatically = False

    def _on_column_header_clicked(self, logical_index):
        """Click a column header to collapse it to a small square (just
        the header height wide) or restore it to the shared column
        width."""

        if logical_index in self.collapsed_columns:
            self.collapsed_columns.discard(logical_index)
            self._set_columns_width([logical_index], self._current_column_width)
        else:
            self.collapsed_columns.add(logical_index)
            square = self.table.horizontalHeader().height()
            self._set_columns_width([logical_index], square)
        self.table_model.set_collapsed_columns(self.collapsed_columns)
        self.proxy.invalidateFilter()

    def _on_column_resized(self, logical_index, _old_size, new_size):
        """Dragging one column resizes every other non-collapsed column to
        match, keeping them uniform (collapsed columns are left alone)."""

        if self._resizing_programmatically or logical_index in self.collapsed_columns:
            return

        self._current_column_width = new_size
        others = (
            c for c in range(self.table_model.columnCount())
            if c != logical_index and c not in self.collapsed_columns
        )
        self._set_columns_width(others, new_size)

    def _autosize_row_header(self):
        """Sizes the vertical header (Symbol/Type label) to the widest
        label via plain text metrics — not QHeaderView.ResizeToContents,
        which computes a sizeHint per row from cell content across the
        whole row and is catastrophically slow with thousands of rows.
        Uses resize() rather than setFixedWidth() so the user can still
        drag it wider/narrower afterward (resize mode stays Interactive)."""

        row_count = self.table_model.rowCount()
        if row_count == 0:
            return

        header = self.table.verticalHeader()
        metrics = header.fontMetrics()
        padding = 24
        widest = max(
            metrics.horizontalAdvance(str(self.table_model.headerData(r, Qt.Vertical) or ""))
            for r in range(row_count)
        )
        header.resize(widest + padding, header.height())



def parse_args(argv):
    parser = argparse.ArgumentParser(
        prog="gui.py",
        description="PySide6 viewer for <variant>.kconfig.json snapshots.",
    )
    parser.add_argument(
        "paths",
        nargs="*",
        metavar="FILE_OR_DIR",
        help="snapshot file(s), or folder(s) containing *.kconfig.json files",
    )
    parser.add_argument(
        "--diff",
        action="store_true",
        help="compare directories: PATHS must all be directories containing "
        "the same *.kconfig.json filenames; opens one tab per unique "
        "filename, with one column per directory",
    )
    args = parser.parse_args(argv)

    if args.diff:
        for p in args.paths:
            if not Path(p).is_dir():
                parser.error(f"--diff requires directories, got a file: {p}")

    return args


def build_diff_tabs(dirs):
    """One tab per unique *.kconfig.json filename found across 'dirs',
    with one column per directory (labeled "<board> [<dir>]", since every
    column in a tab comes from the same board — the directory is what
    tells them apart). A directory missing a given filename gets an empty
    placeholder column labeled "(missing) [<dir>]"."""

    dir_paths = [Path(d) for d in dirs]
    filenames = sorted(
        {p.name for d in dir_paths for p in d.glob("*.kconfig.json")}
    )

    tabs = []
    for filename in filenames:
        snapshots = {}
        for d in dir_paths:
            file_path = d / filename
            if file_path.exists():
                snap = km.load_snapshot(file_path)
                board = snap["board"]
            else:
                snap = {
                    "board": None,
                    "variant": None,
                    "target": None,
                    "symbols": {},
                }
                board = "(missing)"
            snapshots[f"{board} [{d.name}]"] = snap
        title = filename.removesuffix(".kconfig.json")
        tabs.append((title, snapshots))
    return tabs


def main():
    args = parse_args(sys.argv[1:])

    # Parse our own args first so --help/-h works without Qt swallowing it or
    # complaining about an unrecognized option; only pass argv[0] to Qt.
    app = QApplication(sys.argv[:1])

    # Qt's C++ event loop never yields back to the Python interpreter, so
    # Python's own SIGINT handler (which needs interpreter reentry to raise
    # KeyboardInterrupt) never gets a chance to run: Ctrl-C in the terminal
    # is otherwise silently ignored. Restoring the OS default handler makes
    # the process terminate immediately on SIGINT, like any other CLI tool.
    signal.signal(signal.SIGINT, signal.SIG_DFL)

    if args.diff:
        tabs = build_diff_tabs(args.paths)
    else:
        snapshots = {}
        for path in args.paths:
            snapshots.update(km.load_snapshots(path))
        tabs = [("Snapshots", snapshots)]

    window = MainWindow(tabs)
    if args.diff: # automatically show only differing symbols when comparing directories
        window.diff_combo.setCurrentText("differing")
    window.resize(1200, 700)
    window.show()
    window.table.setFocus()

    sys.exit(app.exec())


if __name__ == "__main__":
    main()
