name=WiFi
version=1.0.0
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=Enables WIFI connection
paragraph=With this library you can use the WiFi to connect to Internet.
category=Communication
url=https://github.com/arduino/ArduinoCore-zephyr/tree/master/libraries/WiFi
architectures=renesas,renesas_portenta
includes=WiFi.h
