name=Camera
version=1.0
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=Library to retrieve the die temperature of the processor from zephyr.
paragraph=The Arduino CPU Temperature library is a C++ library designed to retrieve the CPU temperature on supported Arduino products.
category=Device Control
url=https://github.com/arduino/ArduinoCore-zephyr/tree/master/libraries/CPUTemperature
architectures=zephyr,zephyr_portenta,zephyr_nicla,zephyr_giga,zephyr_unoq
